name: our_tutor
description: A new Flutter project.

version: 2.8.0+11

# Prevent accidental publishing to pub.dev.
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HELPER
  intl: 0.20.2
  logger: ^2.0.2
  equatable: ^2.0.5
  shared_preferences: ^2.5.3
  video_player: ^2.10.0
  dio: ^5.3.4
  connectivity_plus: ^6.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.0
  formz: ^0.8.0
  email_validator: ^3.0.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.1.1
  image_picker: ^1.0.5
  http_parser: ^4.1.2
  url_launcher: ^6.2.4

  # Login
  google_sign_in: ^6.3.0
  
  # Firebase
  firebase_core: ^3.15.0
  firebase_crashlytics: ^4.3.8

  # WIDGET
  syncfusion_flutter_pdfviewer: ^30.1.38
  flutter_svg: ^2.2.0
  flutter_rating_bar: ^4.0.1
  bot_toast: ^4.0.3
  cached_network_image: ^3.2.3
  # jitsi_meet_wrapper: ^0.2.0+1
  table_calendar: ^3.0.9
  speech_to_text: ^7.1.0
  dropdown_button2: ^2.1.0
  animated_text_kit: ^4.2.2
  chewie: ^1.12.1

  # STATE MANAGEMENT
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  get_it: ^8.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.3.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_splash.png
  color_dark: "#ffffff"
  image_dark: assets/images/logo_splash.png

  android_12:
    image: assets/images/logo_splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo_splash.png
    icon_background_color_dark: "#ffffff"

  web: false

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  # # Enable generation of localized Strings from arb files.
  generate: true
  fonts:
    - family: Roboto
      fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icon_national/
    - assets/image_tutor/